/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"time"
)

// InlineResponse2007Items struct for InlineResponse2007Items
type InlineResponse2007Items struct {
	// The unique ID of the workflow.
	Id string `json:"id"`
	// The VCS branch of a Workflow's trigger.
	Branch string `json:"branch"`
	// The duration in seconds of a run.
	Duration int64 `json:"duration"`
	// The date and time the workflow was created.
	CreatedAt time.Time `json:"created_at"`
	// The date and time the workflow stopped.
	StoppedAt time.Time `json:"stopped_at"`
	// The number of credits used during execution. Note that Insights is not a real time financial reporting tool and should not be used for credit reporting.
	CreditsUsed int64 `json:"credits_used"`
	// Workflow status.
	Status string `json:"status"`
}

// NewInlineResponse2007Items instantiates a new InlineResponse2007Items object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse2007Items(id string, branch string, duration int64, createdAt time.Time, stoppedAt time.Time, creditsUsed int64, status string) *InlineResponse2007Items {
	this := InlineResponse2007Items{}
	this.Id = id
	this.Branch = branch
	this.Duration = duration
	this.CreatedAt = createdAt
	this.StoppedAt = stoppedAt
	this.CreditsUsed = creditsUsed
	this.Status = status
	return &this
}

// NewInlineResponse2007ItemsWithDefaults instantiates a new InlineResponse2007Items object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse2007ItemsWithDefaults() *InlineResponse2007Items {
	this := InlineResponse2007Items{}
	return &this
}

// GetId returns the Id field value
func (o *InlineResponse2007Items) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2007Items) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *InlineResponse2007Items) SetId(v string) {
	o.Id = v
}

// GetBranch returns the Branch field value
func (o *InlineResponse2007Items) GetBranch() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Branch
}

// GetBranchOk returns a tuple with the Branch field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2007Items) GetBranchOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Branch, true
}

// SetBranch sets field value
func (o *InlineResponse2007Items) SetBranch(v string) {
	o.Branch = v
}

// GetDuration returns the Duration field value
func (o *InlineResponse2007Items) GetDuration() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Duration
}

// GetDurationOk returns a tuple with the Duration field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2007Items) GetDurationOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Duration, true
}

// SetDuration sets field value
func (o *InlineResponse2007Items) SetDuration(v int64) {
	o.Duration = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *InlineResponse2007Items) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2007Items) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *InlineResponse2007Items) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetStoppedAt returns the StoppedAt field value
func (o *InlineResponse2007Items) GetStoppedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.StoppedAt
}

// GetStoppedAtOk returns a tuple with the StoppedAt field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2007Items) GetStoppedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StoppedAt, true
}

// SetStoppedAt sets field value
func (o *InlineResponse2007Items) SetStoppedAt(v time.Time) {
	o.StoppedAt = v
}

// GetCreditsUsed returns the CreditsUsed field value
func (o *InlineResponse2007Items) GetCreditsUsed() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CreditsUsed
}

// GetCreditsUsedOk returns a tuple with the CreditsUsed field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2007Items) GetCreditsUsedOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreditsUsed, true
}

// SetCreditsUsed sets field value
func (o *InlineResponse2007Items) SetCreditsUsed(v int64) {
	o.CreditsUsed = v
}

// GetStatus returns the Status field value
func (o *InlineResponse2007Items) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2007Items) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *InlineResponse2007Items) SetStatus(v string) {
	o.Status = v
}

func (o InlineResponse2007Items) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["branch"] = o.Branch
	}
	if true {
		toSerialize["duration"] = o.Duration
	}
	if true {
		toSerialize["created_at"] = o.CreatedAt
	}
	if true {
		toSerialize["stopped_at"] = o.StoppedAt
	}
	if true {
		toSerialize["credits_used"] = o.CreditsUsed
	}
	if true {
		toSerialize["status"] = o.Status
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse2007Items struct {
	value *InlineResponse2007Items
	isSet bool
}

func (v NullableInlineResponse2007Items) Get() *InlineResponse2007Items {
	return v.value
}

func (v *NullableInlineResponse2007Items) Set(val *InlineResponse2007Items) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse2007Items) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse2007Items) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse2007Items(val *InlineResponse2007Items) *NullableInlineResponse2007Items {
	return &NullableInlineResponse2007Items{value: val, isSet: true}
}

func (v NullableInlineResponse2007Items) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse2007Items) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
