/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineResponse2004OrgData Aggregated metrics for an org, with trends.
type InlineResponse2004OrgData struct {
	Metrics InlineResponse2004OrgDataMetrics `json:"metrics"`
	Trends  InlineResponse2004OrgDataTrends  `json:"trends"`
}

// NewInlineResponse2004OrgData instantiates a new InlineResponse2004OrgData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse2004OrgData(metrics InlineResponse2004OrgDataMetrics, trends InlineResponse2004OrgDataTrends) *InlineResponse2004OrgData {
	this := InlineResponse2004OrgData{}
	this.Metrics = metrics
	this.Trends = trends
	return &this
}

// NewInlineResponse2004OrgDataWithDefaults instantiates a new InlineResponse2004OrgData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse2004OrgDataWithDefaults() *InlineResponse2004OrgData {
	this := InlineResponse2004OrgData{}
	return &this
}

// GetMetrics returns the Metrics field value
func (o *InlineResponse2004OrgData) GetMetrics() InlineResponse2004OrgDataMetrics {
	if o == nil {
		var ret InlineResponse2004OrgDataMetrics
		return ret
	}

	return o.Metrics
}

// GetMetricsOk returns a tuple with the Metrics field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2004OrgData) GetMetricsOk() (*InlineResponse2004OrgDataMetrics, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metrics, true
}

// SetMetrics sets field value
func (o *InlineResponse2004OrgData) SetMetrics(v InlineResponse2004OrgDataMetrics) {
	o.Metrics = v
}

// GetTrends returns the Trends field value
func (o *InlineResponse2004OrgData) GetTrends() InlineResponse2004OrgDataTrends {
	if o == nil {
		var ret InlineResponse2004OrgDataTrends
		return ret
	}

	return o.Trends
}

// GetTrendsOk returns a tuple with the Trends field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2004OrgData) GetTrendsOk() (*InlineResponse2004OrgDataTrends, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Trends, true
}

// SetTrends sets field value
func (o *InlineResponse2004OrgData) SetTrends(v InlineResponse2004OrgDataTrends) {
	o.Trends = v
}

func (o InlineResponse2004OrgData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["metrics"] = o.Metrics
	}
	if true {
		toSerialize["trends"] = o.Trends
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse2004OrgData struct {
	value *InlineResponse2004OrgData
	isSet bool
}

func (v NullableInlineResponse2004OrgData) Get() *InlineResponse2004OrgData {
	return v.value
}

func (v *NullableInlineResponse2004OrgData) Set(val *InlineResponse2004OrgData) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse2004OrgData) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse2004OrgData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse2004OrgData(val *InlineResponse2004OrgData) *NullableInlineResponse2004OrgData {
	return &NullableInlineResponse2004OrgData{value: val, isSet: true}
}

func (v NullableInlineResponse2004OrgData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse2004OrgData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
