/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineResponse20011 Project level test metrics response
type InlineResponse20011 struct {
	// The average number of tests executed per run
	AverageTestCount int64 `json:"average_test_count"`
	// Metrics for the most frequently failing tests
	MostFailedTests []InlineResponse20011MostFailedTests `json:"most_failed_tests"`
	// The number of tests with the same success rate being omitted from most_failed_tests
	MostFailedTestsExtra int64 `json:"most_failed_tests_extra"`
	// Metrics for the slowest running tests
	SlowestTests []InlineResponse20011MostFailedTests `json:"slowest_tests"`
	// The number of tests with the same duration rate being omitted from slowest_tests
	SlowestTestsExtra int64 `json:"slowest_tests_extra"`
	// The total number of test runs
	TotalTestRuns int64 `json:"total_test_runs"`
	// Test counts grouped by pipeline number and workflow id
	TestRuns []InlineResponse20011TestRuns `json:"test_runs"`
}

// NewInlineResponse20011 instantiates a new InlineResponse20011 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse20011(averageTestCount int64, mostFailedTests []InlineResponse20011MostFailedTests, mostFailedTestsExtra int64, slowestTests []InlineResponse20011MostFailedTests, slowestTestsExtra int64, totalTestRuns int64, testRuns []InlineResponse20011TestRuns) *InlineResponse20011 {
	this := InlineResponse20011{}
	this.AverageTestCount = averageTestCount
	this.MostFailedTests = mostFailedTests
	this.MostFailedTestsExtra = mostFailedTestsExtra
	this.SlowestTests = slowestTests
	this.SlowestTestsExtra = slowestTestsExtra
	this.TotalTestRuns = totalTestRuns
	this.TestRuns = testRuns
	return &this
}

// NewInlineResponse20011WithDefaults instantiates a new InlineResponse20011 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse20011WithDefaults() *InlineResponse20011 {
	this := InlineResponse20011{}
	return &this
}

// GetAverageTestCount returns the AverageTestCount field value
func (o *InlineResponse20011) GetAverageTestCount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.AverageTestCount
}

// GetAverageTestCountOk returns a tuple with the AverageTestCount field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20011) GetAverageTestCountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AverageTestCount, true
}

// SetAverageTestCount sets field value
func (o *InlineResponse20011) SetAverageTestCount(v int64) {
	o.AverageTestCount = v
}

// GetMostFailedTests returns the MostFailedTests field value
func (o *InlineResponse20011) GetMostFailedTests() []InlineResponse20011MostFailedTests {
	if o == nil {
		var ret []InlineResponse20011MostFailedTests
		return ret
	}

	return o.MostFailedTests
}

// GetMostFailedTestsOk returns a tuple with the MostFailedTests field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20011) GetMostFailedTestsOk() ([]InlineResponse20011MostFailedTests, bool) {
	if o == nil {
		return nil, false
	}
	return o.MostFailedTests, true
}

// SetMostFailedTests sets field value
func (o *InlineResponse20011) SetMostFailedTests(v []InlineResponse20011MostFailedTests) {
	o.MostFailedTests = v
}

// GetMostFailedTestsExtra returns the MostFailedTestsExtra field value
func (o *InlineResponse20011) GetMostFailedTestsExtra() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.MostFailedTestsExtra
}

// GetMostFailedTestsExtraOk returns a tuple with the MostFailedTestsExtra field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20011) GetMostFailedTestsExtraOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MostFailedTestsExtra, true
}

// SetMostFailedTestsExtra sets field value
func (o *InlineResponse20011) SetMostFailedTestsExtra(v int64) {
	o.MostFailedTestsExtra = v
}

// GetSlowestTests returns the SlowestTests field value
func (o *InlineResponse20011) GetSlowestTests() []InlineResponse20011MostFailedTests {
	if o == nil {
		var ret []InlineResponse20011MostFailedTests
		return ret
	}

	return o.SlowestTests
}

// GetSlowestTestsOk returns a tuple with the SlowestTests field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20011) GetSlowestTestsOk() ([]InlineResponse20011MostFailedTests, bool) {
	if o == nil {
		return nil, false
	}
	return o.SlowestTests, true
}

// SetSlowestTests sets field value
func (o *InlineResponse20011) SetSlowestTests(v []InlineResponse20011MostFailedTests) {
	o.SlowestTests = v
}

// GetSlowestTestsExtra returns the SlowestTestsExtra field value
func (o *InlineResponse20011) GetSlowestTestsExtra() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.SlowestTestsExtra
}

// GetSlowestTestsExtraOk returns a tuple with the SlowestTestsExtra field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20011) GetSlowestTestsExtraOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SlowestTestsExtra, true
}

// SetSlowestTestsExtra sets field value
func (o *InlineResponse20011) SetSlowestTestsExtra(v int64) {
	o.SlowestTestsExtra = v
}

// GetTotalTestRuns returns the TotalTestRuns field value
func (o *InlineResponse20011) GetTotalTestRuns() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.TotalTestRuns
}

// GetTotalTestRunsOk returns a tuple with the TotalTestRuns field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20011) GetTotalTestRunsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalTestRuns, true
}

// SetTotalTestRuns sets field value
func (o *InlineResponse20011) SetTotalTestRuns(v int64) {
	o.TotalTestRuns = v
}

// GetTestRuns returns the TestRuns field value
func (o *InlineResponse20011) GetTestRuns() []InlineResponse20011TestRuns {
	if o == nil {
		var ret []InlineResponse20011TestRuns
		return ret
	}

	return o.TestRuns
}

// GetTestRunsOk returns a tuple with the TestRuns field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20011) GetTestRunsOk() ([]InlineResponse20011TestRuns, bool) {
	if o == nil {
		return nil, false
	}
	return o.TestRuns, true
}

// SetTestRuns sets field value
func (o *InlineResponse20011) SetTestRuns(v []InlineResponse20011TestRuns) {
	o.TestRuns = v
}

func (o InlineResponse20011) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["average_test_count"] = o.AverageTestCount
	}
	if true {
		toSerialize["most_failed_tests"] = o.MostFailedTests
	}
	if true {
		toSerialize["most_failed_tests_extra"] = o.MostFailedTestsExtra
	}
	if true {
		toSerialize["slowest_tests"] = o.SlowestTests
	}
	if true {
		toSerialize["slowest_tests_extra"] = o.SlowestTestsExtra
	}
	if true {
		toSerialize["total_test_runs"] = o.TotalTestRuns
	}
	if true {
		toSerialize["test_runs"] = o.TestRuns
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse20011 struct {
	value *InlineResponse20011
	isSet bool
}

func (v NullableInlineResponse20011) Get() *InlineResponse20011 {
	return v.value
}

func (v *NullableInlineResponse20011) Set(val *InlineResponse20011) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse20011) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse20011) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse20011(val *InlineResponse20011) *NullableInlineResponse20011 {
	return &NullableInlineResponse20011{value: val, isSet: true}
}

func (v NullableInlineResponse20011) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse20011) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
