/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineResponse20010Trends Trends for aggregated metrics acrooss a workflow for a given time window.
type InlineResponse20010Trends struct {
	// The trend value for total number of runs.
	TotalRuns float32 `json:"total_runs"`
	// The trend value for number of failed runs.
	FailedRuns float32 `json:"failed_runs"`
	// The trend value for the success rate.
	SuccessRate float32 `json:"success_rate"`
	// Trend value for the 95th percentile duration for a workflow for a given time window.
	P95DurationSecs float32 `json:"p95_duration_secs"`
	// Trend value for the 50th percentile duration for a workflow for a given time window.
	MedianDurationSecs float32 `json:"median_duration_secs"`
	// The trend value for total credits consumed.
	TotalCreditsUsed float32 `json:"total_credits_used"`
	// trend for mean time to recovery (mean time between failures and their next success).
	Mttr float32 `json:"mttr"`
	// Trend value for the average number of runs per day.
	Throughput float32 `json:"throughput"`
}

// NewInlineResponse20010Trends instantiates a new InlineResponse20010Trends object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse20010Trends(totalRuns float32, failedRuns float32, successRate float32, p95DurationSecs float32, medianDurationSecs float32, totalCreditsUsed float32, mttr float32, throughput float32) *InlineResponse20010Trends {
	this := InlineResponse20010Trends{}
	this.TotalRuns = totalRuns
	this.FailedRuns = failedRuns
	this.SuccessRate = successRate
	this.P95DurationSecs = p95DurationSecs
	this.MedianDurationSecs = medianDurationSecs
	this.TotalCreditsUsed = totalCreditsUsed
	this.Mttr = mttr
	this.Throughput = throughput
	return &this
}

// NewInlineResponse20010TrendsWithDefaults instantiates a new InlineResponse20010Trends object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse20010TrendsWithDefaults() *InlineResponse20010Trends {
	this := InlineResponse20010Trends{}
	return &this
}

// GetTotalRuns returns the TotalRuns field value
func (o *InlineResponse20010Trends) GetTotalRuns() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.TotalRuns
}

// GetTotalRunsOk returns a tuple with the TotalRuns field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20010Trends) GetTotalRunsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalRuns, true
}

// SetTotalRuns sets field value
func (o *InlineResponse20010Trends) SetTotalRuns(v float32) {
	o.TotalRuns = v
}

// GetFailedRuns returns the FailedRuns field value
func (o *InlineResponse20010Trends) GetFailedRuns() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.FailedRuns
}

// GetFailedRunsOk returns a tuple with the FailedRuns field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20010Trends) GetFailedRunsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FailedRuns, true
}

// SetFailedRuns sets field value
func (o *InlineResponse20010Trends) SetFailedRuns(v float32) {
	o.FailedRuns = v
}

// GetSuccessRate returns the SuccessRate field value
func (o *InlineResponse20010Trends) GetSuccessRate() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.SuccessRate
}

// GetSuccessRateOk returns a tuple with the SuccessRate field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20010Trends) GetSuccessRateOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SuccessRate, true
}

// SetSuccessRate sets field value
func (o *InlineResponse20010Trends) SetSuccessRate(v float32) {
	o.SuccessRate = v
}

// GetP95DurationSecs returns the P95DurationSecs field value
func (o *InlineResponse20010Trends) GetP95DurationSecs() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.P95DurationSecs
}

// GetP95DurationSecsOk returns a tuple with the P95DurationSecs field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20010Trends) GetP95DurationSecsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.P95DurationSecs, true
}

// SetP95DurationSecs sets field value
func (o *InlineResponse20010Trends) SetP95DurationSecs(v float32) {
	o.P95DurationSecs = v
}

// GetMedianDurationSecs returns the MedianDurationSecs field value
func (o *InlineResponse20010Trends) GetMedianDurationSecs() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.MedianDurationSecs
}

// GetMedianDurationSecsOk returns a tuple with the MedianDurationSecs field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20010Trends) GetMedianDurationSecsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MedianDurationSecs, true
}

// SetMedianDurationSecs sets field value
func (o *InlineResponse20010Trends) SetMedianDurationSecs(v float32) {
	o.MedianDurationSecs = v
}

// GetTotalCreditsUsed returns the TotalCreditsUsed field value
func (o *InlineResponse20010Trends) GetTotalCreditsUsed() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.TotalCreditsUsed
}

// GetTotalCreditsUsedOk returns a tuple with the TotalCreditsUsed field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20010Trends) GetTotalCreditsUsedOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalCreditsUsed, true
}

// SetTotalCreditsUsed sets field value
func (o *InlineResponse20010Trends) SetTotalCreditsUsed(v float32) {
	o.TotalCreditsUsed = v
}

// GetMttr returns the Mttr field value
func (o *InlineResponse20010Trends) GetMttr() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Mttr
}

// GetMttrOk returns a tuple with the Mttr field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20010Trends) GetMttrOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mttr, true
}

// SetMttr sets field value
func (o *InlineResponse20010Trends) SetMttr(v float32) {
	o.Mttr = v
}

// GetThroughput returns the Throughput field value
func (o *InlineResponse20010Trends) GetThroughput() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Throughput
}

// GetThroughputOk returns a tuple with the Throughput field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20010Trends) GetThroughputOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Throughput, true
}

// SetThroughput sets field value
func (o *InlineResponse20010Trends) SetThroughput(v float32) {
	o.Throughput = v
}

func (o InlineResponse20010Trends) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["total_runs"] = o.TotalRuns
	}
	if true {
		toSerialize["failed_runs"] = o.FailedRuns
	}
	if true {
		toSerialize["success_rate"] = o.SuccessRate
	}
	if true {
		toSerialize["p95_duration_secs"] = o.P95DurationSecs
	}
	if true {
		toSerialize["median_duration_secs"] = o.MedianDurationSecs
	}
	if true {
		toSerialize["total_credits_used"] = o.TotalCreditsUsed
	}
	if true {
		toSerialize["mttr"] = o.Mttr
	}
	if true {
		toSerialize["throughput"] = o.Throughput
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse20010Trends struct {
	value *InlineResponse20010Trends
	isSet bool
}

func (v NullableInlineResponse20010Trends) Get() *InlineResponse20010Trends {
	return v.value
}

func (v *NullableInlineResponse20010Trends) Set(val *InlineResponse20010Trends) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse20010Trends) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse20010Trends) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse20010Trends(val *InlineResponse20010Trends) *NullableInlineResponse20010Trends {
	return &NullableInlineResponse20010Trends{value: val, isSet: true}
}

func (v NullableInlineResponse20010Trends) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse20010Trends) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
