/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// PipelineListResponseTriggerActor The user who triggered the Pipeline.
type PipelineListResponseTriggerActor struct {
	// The login information for the user on the VCS.
	Login string `json:"login"`
	// URL to the user's avatar on the VCS
	AvatarUrl string `json:"avatar_url"`
}

// NewPipelineListResponseTriggerActor instantiates a new PipelineListResponseTriggerActor object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPipelineListResponseTriggerActor(login string, avatarUrl string) *PipelineListResponseTriggerActor {
	this := PipelineListResponseTriggerActor{}
	this.Login = login
	this.AvatarUrl = avatarUrl
	return &this
}

// NewPipelineListResponseTriggerActorWithDefaults instantiates a new PipelineListResponseTriggerActor object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPipelineListResponseTriggerActorWithDefaults() *PipelineListResponseTriggerActor {
	this := PipelineListResponseTriggerActor{}
	return &this
}

// GetLogin returns the Login field value
func (o *PipelineListResponseTriggerActor) GetLogin() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Login
}

// GetLoginOk returns a tuple with the Login field value
// and a boolean to check if the value has been set.
func (o *PipelineListResponseTriggerActor) GetLoginOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Login, true
}

// SetLogin sets field value
func (o *PipelineListResponseTriggerActor) SetLogin(v string) {
	o.Login = v
}

// GetAvatarUrl returns the AvatarUrl field value
func (o *PipelineListResponseTriggerActor) GetAvatarUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AvatarUrl
}

// GetAvatarUrlOk returns a tuple with the AvatarUrl field value
// and a boolean to check if the value has been set.
func (o *PipelineListResponseTriggerActor) GetAvatarUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AvatarUrl, true
}

// SetAvatarUrl sets field value
func (o *PipelineListResponseTriggerActor) SetAvatarUrl(v string) {
	o.AvatarUrl = v
}

func (o PipelineListResponseTriggerActor) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["login"] = o.Login
	}
	if true {
		toSerialize["avatar_url"] = o.AvatarUrl
	}
	return json.Marshal(toSerialize)
}

type NullablePipelineListResponseTriggerActor struct {
	value *PipelineListResponseTriggerActor
	isSet bool
}

func (v NullablePipelineListResponseTriggerActor) Get() *PipelineListResponseTriggerActor {
	return v.value
}

func (v *NullablePipelineListResponseTriggerActor) Set(val *PipelineListResponseTriggerActor) {
	v.value = val
	v.isSet = true
}

func (v NullablePipelineListResponseTriggerActor) IsSet() bool {
	return v.isSet
}

func (v *NullablePipelineListResponseTriggerActor) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePipelineListResponseTriggerActor(val *PipelineListResponseTriggerActor) *NullablePipelineListResponseTriggerActor {
	return &NullablePipelineListResponseTriggerActor{value: val, isSet: true}
}

func (v NullablePipelineListResponseTriggerActor) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePipelineListResponseTriggerActor) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
