/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"time"
)

// InlineResponse2001Items struct for InlineResponse2001Items
type InlineResponse2001Items struct {
	// The name of the environment variable
	Variable string `json:"variable"`
	// The date and time the environment variable was created.
	CreatedAt time.Time `json:"created_at"`
	// ID of the context (UUID)
	ContextId string `json:"context_id"`
}

// NewInlineResponse2001Items instantiates a new InlineResponse2001Items object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse2001Items(variable string, createdAt time.Time, contextId string) *InlineResponse2001Items {
	this := InlineResponse2001Items{}
	this.Variable = variable
	this.CreatedAt = createdAt
	this.ContextId = contextId
	return &this
}

// NewInlineResponse2001ItemsWithDefaults instantiates a new InlineResponse2001Items object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse2001ItemsWithDefaults() *InlineResponse2001Items {
	this := InlineResponse2001Items{}
	return &this
}

// GetVariable returns the Variable field value
func (o *InlineResponse2001Items) GetVariable() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Variable
}

// GetVariableOk returns a tuple with the Variable field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2001Items) GetVariableOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Variable, true
}

// SetVariable sets field value
func (o *InlineResponse2001Items) SetVariable(v string) {
	o.Variable = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *InlineResponse2001Items) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2001Items) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *InlineResponse2001Items) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetContextId returns the ContextId field value
func (o *InlineResponse2001Items) GetContextId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContextId
}

// GetContextIdOk returns a tuple with the ContextId field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2001Items) GetContextIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContextId, true
}

// SetContextId sets field value
func (o *InlineResponse2001Items) SetContextId(v string) {
	o.ContextId = v
}

func (o InlineResponse2001Items) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["variable"] = o.Variable
	}
	if true {
		toSerialize["created_at"] = o.CreatedAt
	}
	if true {
		toSerialize["context_id"] = o.ContextId
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse2001Items struct {
	value *InlineResponse2001Items
	isSet bool
}

func (v NullableInlineResponse2001Items) Get() *InlineResponse2001Items {
	return v.value
}

func (v *NullableInlineResponse2001Items) Set(val *InlineResponse2001Items) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse2001Items) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse2001Items) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse2001Items(val *InlineResponse2001Items) *NullableInlineResponse2001Items {
	return &NullableInlineResponse2001Items{value: val, isSet: true}
}

func (v NullableInlineResponse2001Items) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse2001Items) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
