/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// User1 The attribution actor who will run the scheduled pipeline.
type User1 struct {
	// The unique ID of the user.
	Id string `json:"id"`
	// The login information for the user on the VCS.
	Login string `json:"login"`
	// The name of the user.
	Name string `json:"name"`
}

// NewUser1 instantiates a new User1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUser1(id string, login string, name string) *User1 {
	this := User1{}
	this.Id = id
	this.Login = login
	this.Name = name
	return &this
}

// NewUser1WithDefaults instantiates a new User1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUser1WithDefaults() *User1 {
	this := User1{}
	return &this
}

// GetId returns the Id field value
func (o *User1) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *User1) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *User1) SetId(v string) {
	o.Id = v
}

// GetLogin returns the Login field value
func (o *User1) GetLogin() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Login
}

// GetLoginOk returns a tuple with the Login field value
// and a boolean to check if the value has been set.
func (o *User1) GetLoginOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Login, true
}

// SetLogin sets field value
func (o *User1) SetLogin(v string) {
	o.Login = v
}

// GetName returns the Name field value
func (o *User1) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *User1) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *User1) SetName(v string) {
	o.Name = v
}

func (o User1) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["login"] = o.Login
	}
	if true {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableUser1 struct {
	value *User1
	isSet bool
}

func (v NullableUser1) Get() *User1 {
	return v.value
}

func (v *NullableUser1) Set(val *User1) {
	v.value = val
	v.isSet = true
}

func (v NullableUser1) IsSet() bool {
	return v.isSet
}

func (v *NullableUser1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUser1(val *User1) *NullableUser1 {
	return &NullableUser1{value: val, isSet: true}
}

func (v NullableUser1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUser1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
