/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"time"
)

// InlineResponse2003Items struct for InlineResponse2003Items
type InlineResponse2003Items struct {
	// The name of the workflow.
	Name string `json:"name"`
	// The start time for the earliest execution included in the metrics.
	MinStartedAt time.Time `json:"min_started_at"`
	// The end time of the last execution included in the metrics.
	MaxEndedAt time.Time `json:"max_ended_at"`
	// The start of the interval for timeseries metrics.
	Timestamp time.Time                 `json:"timestamp"`
	Metrics   InlineResponse2003Metrics `json:"metrics"`
}

// NewInlineResponse2003Items instantiates a new InlineResponse2003Items object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse2003Items(name string, minStartedAt time.Time, maxEndedAt time.Time, timestamp time.Time, metrics InlineResponse2003Metrics) *InlineResponse2003Items {
	this := InlineResponse2003Items{}
	this.Name = name
	this.MinStartedAt = minStartedAt
	this.MaxEndedAt = maxEndedAt
	this.Timestamp = timestamp
	this.Metrics = metrics
	return &this
}

// NewInlineResponse2003ItemsWithDefaults instantiates a new InlineResponse2003Items object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse2003ItemsWithDefaults() *InlineResponse2003Items {
	this := InlineResponse2003Items{}
	return &this
}

// GetName returns the Name field value
func (o *InlineResponse2003Items) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2003Items) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *InlineResponse2003Items) SetName(v string) {
	o.Name = v
}

// GetMinStartedAt returns the MinStartedAt field value
func (o *InlineResponse2003Items) GetMinStartedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.MinStartedAt
}

// GetMinStartedAtOk returns a tuple with the MinStartedAt field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2003Items) GetMinStartedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MinStartedAt, true
}

// SetMinStartedAt sets field value
func (o *InlineResponse2003Items) SetMinStartedAt(v time.Time) {
	o.MinStartedAt = v
}

// GetMaxEndedAt returns the MaxEndedAt field value
func (o *InlineResponse2003Items) GetMaxEndedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.MaxEndedAt
}

// GetMaxEndedAtOk returns a tuple with the MaxEndedAt field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2003Items) GetMaxEndedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxEndedAt, true
}

// SetMaxEndedAt sets field value
func (o *InlineResponse2003Items) SetMaxEndedAt(v time.Time) {
	o.MaxEndedAt = v
}

// GetTimestamp returns the Timestamp field value
func (o *InlineResponse2003Items) GetTimestamp() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2003Items) GetTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *InlineResponse2003Items) SetTimestamp(v time.Time) {
	o.Timestamp = v
}

// GetMetrics returns the Metrics field value
func (o *InlineResponse2003Items) GetMetrics() InlineResponse2003Metrics {
	if o == nil {
		var ret InlineResponse2003Metrics
		return ret
	}

	return o.Metrics
}

// GetMetricsOk returns a tuple with the Metrics field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2003Items) GetMetricsOk() (*InlineResponse2003Metrics, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metrics, true
}

// SetMetrics sets field value
func (o *InlineResponse2003Items) SetMetrics(v InlineResponse2003Metrics) {
	o.Metrics = v
}

func (o InlineResponse2003Items) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["min_started_at"] = o.MinStartedAt
	}
	if true {
		toSerialize["max_ended_at"] = o.MaxEndedAt
	}
	if true {
		toSerialize["timestamp"] = o.Timestamp
	}
	if true {
		toSerialize["metrics"] = o.Metrics
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse2003Items struct {
	value *InlineResponse2003Items
	isSet bool
}

func (v NullableInlineResponse2003Items) Get() *InlineResponse2003Items {
	return v.value
}

func (v *NullableInlineResponse2003Items) Set(val *InlineResponse2003Items) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse2003Items) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse2003Items) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse2003Items(val *InlineResponse2003Items) *NullableInlineResponse2003Items {
	return &NullableInlineResponse2003Items{value: val, isSet: true}
}

func (v NullableInlineResponse2003Items) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse2003Items) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
