/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineResponse20010 Workflow level aggregated metrics and trends response
type InlineResponse20010 struct {
	Metrics InlineResponse20010Metrics `json:"metrics"`
	Trends  InlineResponse20010Trends  `json:"trends"`
	// A list of all the workflow names for a given project.
	WorkflowNames []string `json:"workflow_names"`
}

// NewInlineResponse20010 instantiates a new InlineResponse20010 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse20010(metrics InlineResponse20010Metrics, trends InlineResponse20010Trends, workflowNames []string) *InlineResponse20010 {
	this := InlineResponse20010{}
	this.Metrics = metrics
	this.Trends = trends
	this.WorkflowNames = workflowNames
	return &this
}

// NewInlineResponse20010WithDefaults instantiates a new InlineResponse20010 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse20010WithDefaults() *InlineResponse20010 {
	this := InlineResponse20010{}
	return &this
}

// GetMetrics returns the Metrics field value
func (o *InlineResponse20010) GetMetrics() InlineResponse20010Metrics {
	if o == nil {
		var ret InlineResponse20010Metrics
		return ret
	}

	return o.Metrics
}

// GetMetricsOk returns a tuple with the Metrics field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20010) GetMetricsOk() (*InlineResponse20010Metrics, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metrics, true
}

// SetMetrics sets field value
func (o *InlineResponse20010) SetMetrics(v InlineResponse20010Metrics) {
	o.Metrics = v
}

// GetTrends returns the Trends field value
func (o *InlineResponse20010) GetTrends() InlineResponse20010Trends {
	if o == nil {
		var ret InlineResponse20010Trends
		return ret
	}

	return o.Trends
}

// GetTrendsOk returns a tuple with the Trends field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20010) GetTrendsOk() (*InlineResponse20010Trends, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Trends, true
}

// SetTrends sets field value
func (o *InlineResponse20010) SetTrends(v InlineResponse20010Trends) {
	o.Trends = v
}

// GetWorkflowNames returns the WorkflowNames field value
func (o *InlineResponse20010) GetWorkflowNames() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.WorkflowNames
}

// GetWorkflowNamesOk returns a tuple with the WorkflowNames field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20010) GetWorkflowNamesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WorkflowNames, true
}

// SetWorkflowNames sets field value
func (o *InlineResponse20010) SetWorkflowNames(v []string) {
	o.WorkflowNames = v
}

func (o InlineResponse20010) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["metrics"] = o.Metrics
	}
	if true {
		toSerialize["trends"] = o.Trends
	}
	if true {
		toSerialize["workflow_names"] = o.WorkflowNames
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse20010 struct {
	value *InlineResponse20010
	isSet bool
}

func (v NullableInlineResponse20010) Get() *InlineResponse20010 {
	return v.value
}

func (v *NullableInlineResponse20010) Set(val *InlineResponse20010) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse20010) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse20010) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse20010(val *InlineResponse20010) *NullableInlineResponse20010 {
	return &NullableInlineResponse20010{value: val, isSet: true}
}

func (v NullableInlineResponse20010) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse20010) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
