/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineResponse20011MostFailedTests struct for InlineResponse20011MostFailedTests
type InlineResponse20011MostFailedTests struct {
	// The 95th percentile duration, in seconds, among a group of test runs.
	P95Duration float64 `json:"p95_duration"`
	// The total number of times the test was run.
	TotalRuns int64 `json:"total_runs"`
	// The class the test belongs to.
	Classname string `json:"classname"`
	// The number of times the test failed
	FailedRuns int64 `json:"failed_runs"`
	// Whether the test is flaky.
	Flaky bool `json:"flaky"`
	// The source of the test.
	Source string `json:"source"`
	// The file the test belongs to.
	File string `json:"file"`
	// The name of the job.
	JobName string `json:"job_name"`
	// The name of the test.
	TestName string `json:"test_name"`
}

// NewInlineResponse20011MostFailedTests instantiates a new InlineResponse20011MostFailedTests object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse20011MostFailedTests(p95Duration float64, totalRuns int64, classname string, failedRuns int64, flaky bool, source string, file string, jobName string, testName string) *InlineResponse20011MostFailedTests {
	this := InlineResponse20011MostFailedTests{}
	this.P95Duration = p95Duration
	this.TotalRuns = totalRuns
	this.Classname = classname
	this.FailedRuns = failedRuns
	this.Flaky = flaky
	this.Source = source
	this.File = file
	this.JobName = jobName
	this.TestName = testName
	return &this
}

// NewInlineResponse20011MostFailedTestsWithDefaults instantiates a new InlineResponse20011MostFailedTests object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse20011MostFailedTestsWithDefaults() *InlineResponse20011MostFailedTests {
	this := InlineResponse20011MostFailedTests{}
	return &this
}

// GetP95Duration returns the P95Duration field value
func (o *InlineResponse20011MostFailedTests) GetP95Duration() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.P95Duration
}

// GetP95DurationOk returns a tuple with the P95Duration field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20011MostFailedTests) GetP95DurationOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.P95Duration, true
}

// SetP95Duration sets field value
func (o *InlineResponse20011MostFailedTests) SetP95Duration(v float64) {
	o.P95Duration = v
}

// GetTotalRuns returns the TotalRuns field value
func (o *InlineResponse20011MostFailedTests) GetTotalRuns() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.TotalRuns
}

// GetTotalRunsOk returns a tuple with the TotalRuns field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20011MostFailedTests) GetTotalRunsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalRuns, true
}

// SetTotalRuns sets field value
func (o *InlineResponse20011MostFailedTests) SetTotalRuns(v int64) {
	o.TotalRuns = v
}

// GetClassname returns the Classname field value
func (o *InlineResponse20011MostFailedTests) GetClassname() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Classname
}

// GetClassnameOk returns a tuple with the Classname field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20011MostFailedTests) GetClassnameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Classname, true
}

// SetClassname sets field value
func (o *InlineResponse20011MostFailedTests) SetClassname(v string) {
	o.Classname = v
}

// GetFailedRuns returns the FailedRuns field value
func (o *InlineResponse20011MostFailedTests) GetFailedRuns() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.FailedRuns
}

// GetFailedRunsOk returns a tuple with the FailedRuns field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20011MostFailedTests) GetFailedRunsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FailedRuns, true
}

// SetFailedRuns sets field value
func (o *InlineResponse20011MostFailedTests) SetFailedRuns(v int64) {
	o.FailedRuns = v
}

// GetFlaky returns the Flaky field value
func (o *InlineResponse20011MostFailedTests) GetFlaky() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Flaky
}

// GetFlakyOk returns a tuple with the Flaky field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20011MostFailedTests) GetFlakyOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Flaky, true
}

// SetFlaky sets field value
func (o *InlineResponse20011MostFailedTests) SetFlaky(v bool) {
	o.Flaky = v
}

// GetSource returns the Source field value
func (o *InlineResponse20011MostFailedTests) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20011MostFailedTests) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *InlineResponse20011MostFailedTests) SetSource(v string) {
	o.Source = v
}

// GetFile returns the File field value
func (o *InlineResponse20011MostFailedTests) GetFile() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.File
}

// GetFileOk returns a tuple with the File field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20011MostFailedTests) GetFileOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.File, true
}

// SetFile sets field value
func (o *InlineResponse20011MostFailedTests) SetFile(v string) {
	o.File = v
}

// GetJobName returns the JobName field value
func (o *InlineResponse20011MostFailedTests) GetJobName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JobName
}

// GetJobNameOk returns a tuple with the JobName field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20011MostFailedTests) GetJobNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobName, true
}

// SetJobName sets field value
func (o *InlineResponse20011MostFailedTests) SetJobName(v string) {
	o.JobName = v
}

// GetTestName returns the TestName field value
func (o *InlineResponse20011MostFailedTests) GetTestName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TestName
}

// GetTestNameOk returns a tuple with the TestName field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20011MostFailedTests) GetTestNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TestName, true
}

// SetTestName sets field value
func (o *InlineResponse20011MostFailedTests) SetTestName(v string) {
	o.TestName = v
}

func (o InlineResponse20011MostFailedTests) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["p95_duration"] = o.P95Duration
	}
	if true {
		toSerialize["total_runs"] = o.TotalRuns
	}
	if true {
		toSerialize["classname"] = o.Classname
	}
	if true {
		toSerialize["failed_runs"] = o.FailedRuns
	}
	if true {
		toSerialize["flaky"] = o.Flaky
	}
	if true {
		toSerialize["source"] = o.Source
	}
	if true {
		toSerialize["file"] = o.File
	}
	if true {
		toSerialize["job_name"] = o.JobName
	}
	if true {
		toSerialize["test_name"] = o.TestName
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse20011MostFailedTests struct {
	value *InlineResponse20011MostFailedTests
	isSet bool
}

func (v NullableInlineResponse20011MostFailedTests) Get() *InlineResponse20011MostFailedTests {
	return v.value
}

func (v *NullableInlineResponse20011MostFailedTests) Set(val *InlineResponse20011MostFailedTests) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse20011MostFailedTests) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse20011MostFailedTests) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse20011MostFailedTests(val *InlineResponse20011MostFailedTests) *NullableInlineResponse20011MostFailedTests {
	return &NullableInlineResponse20011MostFailedTests{value: val, isSet: true}
}

func (v NullableInlineResponse20011MostFailedTests) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse20011MostFailedTests) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
