/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"time"
)

// PipelineListResponseTrigger A summary of the trigger.
type PipelineListResponseTrigger struct {
	// The type of trigger.
	Type string `json:"type"`
	// The date and time the trigger was received.
	ReceivedAt time.Time                        `json:"received_at"`
	Actor      PipelineListResponseTriggerActor `json:"actor"`
}

// NewPipelineListResponseTrigger instantiates a new PipelineListResponseTrigger object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPipelineListResponseTrigger(type_ string, receivedAt time.Time, actor PipelineListResponseTriggerActor) *PipelineListResponseTrigger {
	this := PipelineListResponseTrigger{}
	this.Type = type_
	this.ReceivedAt = receivedAt
	this.Actor = actor
	return &this
}

// NewPipelineListResponseTriggerWithDefaults instantiates a new PipelineListResponseTrigger object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPipelineListResponseTriggerWithDefaults() *PipelineListResponseTrigger {
	this := PipelineListResponseTrigger{}
	return &this
}

// GetType returns the Type field value
func (o *PipelineListResponseTrigger) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *PipelineListResponseTrigger) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PipelineListResponseTrigger) SetType(v string) {
	o.Type = v
}

// GetReceivedAt returns the ReceivedAt field value
func (o *PipelineListResponseTrigger) GetReceivedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ReceivedAt
}

// GetReceivedAtOk returns a tuple with the ReceivedAt field value
// and a boolean to check if the value has been set.
func (o *PipelineListResponseTrigger) GetReceivedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReceivedAt, true
}

// SetReceivedAt sets field value
func (o *PipelineListResponseTrigger) SetReceivedAt(v time.Time) {
	o.ReceivedAt = v
}

// GetActor returns the Actor field value
func (o *PipelineListResponseTrigger) GetActor() PipelineListResponseTriggerActor {
	if o == nil {
		var ret PipelineListResponseTriggerActor
		return ret
	}

	return o.Actor
}

// GetActorOk returns a tuple with the Actor field value
// and a boolean to check if the value has been set.
func (o *PipelineListResponseTrigger) GetActorOk() (*PipelineListResponseTriggerActor, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Actor, true
}

// SetActor sets field value
func (o *PipelineListResponseTrigger) SetActor(v PipelineListResponseTriggerActor) {
	o.Actor = v
}

func (o PipelineListResponseTrigger) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["type"] = o.Type
	}
	if true {
		toSerialize["received_at"] = o.ReceivedAt
	}
	if true {
		toSerialize["actor"] = o.Actor
	}
	return json.Marshal(toSerialize)
}

type NullablePipelineListResponseTrigger struct {
	value *PipelineListResponseTrigger
	isSet bool
}

func (v NullablePipelineListResponseTrigger) Get() *PipelineListResponseTrigger {
	return v.value
}

func (v *NullablePipelineListResponseTrigger) Set(val *PipelineListResponseTrigger) {
	v.value = val
	v.isSet = true
}

func (v NullablePipelineListResponseTrigger) IsSet() bool {
	return v.isSet
}

func (v *NullablePipelineListResponseTrigger) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePipelineListResponseTrigger(val *PipelineListResponseTrigger) *NullablePipelineListResponseTrigger {
	return &NullablePipelineListResponseTrigger{value: val, isSet: true}
}

func (v NullablePipelineListResponseTrigger) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePipelineListResponseTrigger) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
