/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineResponse2002ProjectDataMetrics Metrics aggregated across all workflows and branches for a project.
type InlineResponse2002ProjectDataMetrics struct {
	// The total number of runs.
	TotalRuns int64 `json:"total_runs"`
	// Total duration, in seconds.
	TotalDurationSecs int64 `json:"total_duration_secs"`
	// The total credits consumed over the current timeseries interval.
	TotalCreditsUsed int64   `json:"total_credits_used"`
	SuccessRate      float32 `json:"success_rate"`
	// The average number of runs per day.
	Throughput float32 `json:"throughput"`
}

// NewInlineResponse2002ProjectDataMetrics instantiates a new InlineResponse2002ProjectDataMetrics object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse2002ProjectDataMetrics(totalRuns int64, totalDurationSecs int64, totalCreditsUsed int64, successRate float32, throughput float32) *InlineResponse2002ProjectDataMetrics {
	this := InlineResponse2002ProjectDataMetrics{}
	this.TotalRuns = totalRuns
	this.TotalDurationSecs = totalDurationSecs
	this.TotalCreditsUsed = totalCreditsUsed
	this.SuccessRate = successRate
	this.Throughput = throughput
	return &this
}

// NewInlineResponse2002ProjectDataMetricsWithDefaults instantiates a new InlineResponse2002ProjectDataMetrics object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse2002ProjectDataMetricsWithDefaults() *InlineResponse2002ProjectDataMetrics {
	this := InlineResponse2002ProjectDataMetrics{}
	return &this
}

// GetTotalRuns returns the TotalRuns field value
func (o *InlineResponse2002ProjectDataMetrics) GetTotalRuns() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.TotalRuns
}

// GetTotalRunsOk returns a tuple with the TotalRuns field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2002ProjectDataMetrics) GetTotalRunsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalRuns, true
}

// SetTotalRuns sets field value
func (o *InlineResponse2002ProjectDataMetrics) SetTotalRuns(v int64) {
	o.TotalRuns = v
}

// GetTotalDurationSecs returns the TotalDurationSecs field value
func (o *InlineResponse2002ProjectDataMetrics) GetTotalDurationSecs() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.TotalDurationSecs
}

// GetTotalDurationSecsOk returns a tuple with the TotalDurationSecs field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2002ProjectDataMetrics) GetTotalDurationSecsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalDurationSecs, true
}

// SetTotalDurationSecs sets field value
func (o *InlineResponse2002ProjectDataMetrics) SetTotalDurationSecs(v int64) {
	o.TotalDurationSecs = v
}

// GetTotalCreditsUsed returns the TotalCreditsUsed field value
func (o *InlineResponse2002ProjectDataMetrics) GetTotalCreditsUsed() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.TotalCreditsUsed
}

// GetTotalCreditsUsedOk returns a tuple with the TotalCreditsUsed field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2002ProjectDataMetrics) GetTotalCreditsUsedOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalCreditsUsed, true
}

// SetTotalCreditsUsed sets field value
func (o *InlineResponse2002ProjectDataMetrics) SetTotalCreditsUsed(v int64) {
	o.TotalCreditsUsed = v
}

// GetSuccessRate returns the SuccessRate field value
func (o *InlineResponse2002ProjectDataMetrics) GetSuccessRate() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.SuccessRate
}

// GetSuccessRateOk returns a tuple with the SuccessRate field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2002ProjectDataMetrics) GetSuccessRateOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SuccessRate, true
}

// SetSuccessRate sets field value
func (o *InlineResponse2002ProjectDataMetrics) SetSuccessRate(v float32) {
	o.SuccessRate = v
}

// GetThroughput returns the Throughput field value
func (o *InlineResponse2002ProjectDataMetrics) GetThroughput() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Throughput
}

// GetThroughputOk returns a tuple with the Throughput field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2002ProjectDataMetrics) GetThroughputOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Throughput, true
}

// SetThroughput sets field value
func (o *InlineResponse2002ProjectDataMetrics) SetThroughput(v float32) {
	o.Throughput = v
}

func (o InlineResponse2002ProjectDataMetrics) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["total_runs"] = o.TotalRuns
	}
	if true {
		toSerialize["total_duration_secs"] = o.TotalDurationSecs
	}
	if true {
		toSerialize["total_credits_used"] = o.TotalCreditsUsed
	}
	if true {
		toSerialize["success_rate"] = o.SuccessRate
	}
	if true {
		toSerialize["throughput"] = o.Throughput
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse2002ProjectDataMetrics struct {
	value *InlineResponse2002ProjectDataMetrics
	isSet bool
}

func (v NullableInlineResponse2002ProjectDataMetrics) Get() *InlineResponse2002ProjectDataMetrics {
	return v.value
}

func (v *NullableInlineResponse2002ProjectDataMetrics) Set(val *InlineResponse2002ProjectDataMetrics) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse2002ProjectDataMetrics) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse2002ProjectDataMetrics) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse2002ProjectDataMetrics(val *InlineResponse2002ProjectDataMetrics) *NullableInlineResponse2002ProjectDataMetrics {
	return &NullableInlineResponse2002ProjectDataMetrics{value: val, isSet: true}
}

func (v NullableInlineResponse2002ProjectDataMetrics) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse2002ProjectDataMetrics) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
