//go:build go1.18
// +build go1.18

// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.8.3, generator: @autorest/go@4.0.0-preview.40)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package client

// CircleciClientAddEnvironmentVariableToContextResponse contains the response from method CircleciClient.AddEnvironmentVariableToContext.
type CircleciClientAddEnvironmentVariableToContextResponse struct {
	Paths1Fz7BoxContextIDEnvironmentVariableEnvVarNamePutResponses200ContentApplicationJSONSchema
}

// CircleciClientApprovePendingApprovalJobByIDResponse contains the response from method CircleciClient.ApprovePendingApprovalJobByID.
type CircleciClientApprovePendingApprovalJobByIDResponse struct {
	MessageResponse7
}

// CircleciClientCancelJobResponse contains the response from method CircleciClient.CancelJob.
type CircleciClientCancelJobResponse struct {
	MessageResponse5
}

// CircleciClientCancelWorkflowResponse contains the response from method CircleciClient.CancelWorkflow.
type CircleciClientCancelWorkflowResponse struct {
	MessageResponse8
}

// CircleciClientContinuePipelineResponse contains the response from method CircleciClient.ContinuePipeline.
type CircleciClientContinuePipelineResponse struct {
	MessageResponse2
}

// CircleciClientCreateCheckoutKeyResponse contains the response from method CircleciClient.CreateCheckoutKey.
type CircleciClientCreateCheckoutKeyResponse struct {
	CheckoutKey
}

// CircleciClientCreateContextResponse contains the response from method CircleciClient.CreateContext.
type CircleciClientCreateContextResponse struct {
	Context
}

// CircleciClientCreateEnvVarResponse contains the response from method CircleciClient.CreateEnvVar.
type CircleciClientCreateEnvVarResponse struct {
	EnvironmentVariablePair
}

// CircleciClientCreateScheduleResponse contains the response from method CircleciClient.CreateSchedule.
type CircleciClientCreateScheduleResponse struct {
	Schedule
}

// CircleciClientDeleteCheckoutKeyResponse contains the response from method CircleciClient.DeleteCheckoutKey.
type CircleciClientDeleteCheckoutKeyResponse struct {
	MessageResponse3
}

// CircleciClientDeleteContextResponse contains the response from method CircleciClient.DeleteContext.
type CircleciClientDeleteContextResponse struct {
	MessageResponse
}

// CircleciClientDeleteEnvVarResponse contains the response from method CircleciClient.DeleteEnvVar.
type CircleciClientDeleteEnvVarResponse struct {
	MessageResponse4
}

// CircleciClientDeleteEnvironmentVariableFromContextResponse contains the response from method CircleciClient.DeleteEnvironmentVariableFromContext.
type CircleciClientDeleteEnvironmentVariableFromContextResponse struct {
	MessageResponse0
}

// CircleciClientDeleteScheduleByIDResponse contains the response from method CircleciClient.DeleteScheduleByID.
type CircleciClientDeleteScheduleByIDResponse struct {
	MessageResponse6
}

// CircleciClientGetAllInsightsBranchesResponse contains the response from method CircleciClient.GetAllInsightsBranches.
type CircleciClientGetAllInsightsBranchesResponse struct {
	// Anything
	Interface interface{}
}

// CircleciClientGetCheckoutKeyResponse contains the response from method CircleciClient.GetCheckoutKey.
type CircleciClientGetCheckoutKeyResponse struct {
	CheckoutKey0
}

// CircleciClientGetCollaborationsResponse contains the response from method CircleciClient.GetCollaborations.
type CircleciClientGetCollaborationsResponse struct {
	// Array of get-200-application-json-itemsItem
	Get200ApplicationJSONItemsItemArray []*Get200ApplicationJSONItemsItem
}

// CircleciClientGetContextResponse contains the response from method CircleciClient.GetContext.
type CircleciClientGetContextResponse struct {
	Context0
}

// CircleciClientGetCurrentUserResponse contains the response from method CircleciClient.GetCurrentUser.
type CircleciClientGetCurrentUserResponse struct {
	User
}

// CircleciClientGetEnvVarResponse contains the response from method CircleciClient.GetEnvVar.
type CircleciClientGetEnvVarResponse struct {
	EnvironmentVariablePair1
}

// CircleciClientGetFlakyTestsResponse contains the response from method CircleciClient.GetFlakyTests.
type CircleciClientGetFlakyTestsResponse struct {
	PathsFqa3Z9InsightsProjectSlugFlakyTestsGetResponses200ContentApplicationJSONSchema
}

// CircleciClientGetJobArtifactsResponse contains the response from method CircleciClient.GetJobArtifacts.
type CircleciClientGetJobArtifactsResponse struct {
	ArtifactListResponse
}

// CircleciClientGetJobDetailsResponse contains the response from method CircleciClient.GetJobDetails.
type CircleciClientGetJobDetailsResponse struct {
	JobDetails
}

// CircleciClientGetJobTimeseriesResponse contains the response from method CircleciClient.GetJobTimeseries.
type CircleciClientGetJobTimeseriesResponse struct {
	Paths1Yiabp7InsightsTimeSeriesProjectSlugWorkflowsWorkflowNameJobsGetResponses200ContentApplicationJSONSchema
}

// CircleciClientGetOrgSummaryDataResponse contains the response from method CircleciClient.GetOrgSummaryData.
type CircleciClientGetOrgSummaryDataResponse struct {
	Paths3Qw5G4InsightsOrgSlugSummaryGetResponses200ContentApplicationJSONSchema
}

// CircleciClientGetPipelineByIDResponse contains the response from method CircleciClient.GetPipelineByID.
type CircleciClientGetPipelineByIDResponse struct {
	Pipeline
}

// CircleciClientGetPipelineByNumberResponse contains the response from method CircleciClient.GetPipelineByNumber.
type CircleciClientGetPipelineByNumberResponse struct {
	Pipeline0
}

// CircleciClientGetPipelineConfigByIDResponse contains the response from method CircleciClient.GetPipelineConfigByID.
type CircleciClientGetPipelineConfigByIDResponse struct {
	PipelineConfig
}

// CircleciClientGetProjectBySlugResponse contains the response from method CircleciClient.GetProjectBySlug.
type CircleciClientGetProjectBySlugResponse struct {
	Project
}

// CircleciClientGetProjectJobRunsResponse contains the response from method CircleciClient.GetProjectJobRuns.
type CircleciClientGetProjectJobRunsResponse struct {
	PathsX3FxmxInsightsProjectSlugWorkflowsWorkflowNameJobsJobNameGetResponses200ContentApplicationJSONSchema
}

// CircleciClientGetProjectWorkflowJobMetricsResponse contains the response from method CircleciClient.GetProjectWorkflowJobMetrics.
type CircleciClientGetProjectWorkflowJobMetricsResponse struct {
	PathsXllw8WInsightsProjectSlugWorkflowsWorkflowNameJobsGetResponses200ContentApplicationJSONSchema
}

// CircleciClientGetProjectWorkflowMetricsResponse contains the response from method CircleciClient.GetProjectWorkflowMetrics.
type CircleciClientGetProjectWorkflowMetricsResponse struct {
	PathsUxywyxInsightsProjectSlugWorkflowsGetResponses200ContentApplicationJSONSchema
}

// CircleciClientGetProjectWorkflowRunsResponse contains the response from method CircleciClient.GetProjectWorkflowRuns.
type CircleciClientGetProjectWorkflowRunsResponse struct {
	PathsRd9DcuInsightsProjectSlugWorkflowsWorkflowNameGetResponses200ContentApplicationJSONSchema
}

// CircleciClientGetProjectWorkflowTestMetricsResponse contains the response from method CircleciClient.GetProjectWorkflowTestMetrics.
type CircleciClientGetProjectWorkflowTestMetricsResponse struct {
	Paths17Ss7PbInsightsProjectSlugWorkflowsWorkflowNameTestMetricsGetResponses200ContentApplicationJSONSchema
}

// CircleciClientGetProjectWorkflowsPageDataResponse contains the response from method CircleciClient.GetProjectWorkflowsPageData.
type CircleciClientGetProjectWorkflowsPageDataResponse struct {
	PathsZsvny0InsightsPagesProjectSlugSummaryGetResponses200ContentApplicationJSONSchema
}

// CircleciClientGetScheduleByIDResponse contains the response from method CircleciClient.GetScheduleByID.
type CircleciClientGetScheduleByIDResponse struct {
	Schedule0
}

// CircleciClientGetTestsResponse contains the response from method CircleciClient.GetTests.
type CircleciClientGetTestsResponse struct {
	TestsResponse
}

// CircleciClientGetUserResponse contains the response from method CircleciClient.GetUser.
type CircleciClientGetUserResponse struct {
	User0
}

// CircleciClientGetWorkflowByIDResponse contains the response from method CircleciClient.GetWorkflowByID.
type CircleciClientGetWorkflowByIDResponse struct {
	Workflow
}

// CircleciClientGetWorkflowSummaryResponse contains the response from method CircleciClient.GetWorkflowSummary.
type CircleciClientGetWorkflowSummaryResponse struct {
	PathsSlfcapInsightsProjectSlugWorkflowsWorkflowNameSummaryGetResponses200ContentApplicationJSONSchema
}

// CircleciClientGetWorkflowTimeseriesResponse contains the response from method CircleciClient.GetWorkflowTimeseries.
type CircleciClientGetWorkflowTimeseriesResponse struct {
	Paths1OqdqwuInsightsTimeSeriesProjectSlugWorkflowsGetResponses200ContentApplicationJSONSchema
}

// CircleciClientListCheckoutKeysResponse contains the response from method CircleciClient.ListCheckoutKeys.
type CircleciClientListCheckoutKeysResponse struct {
	CheckoutKeyListResponse
}

// CircleciClientListContextsResponse contains the response from method CircleciClient.ListContexts.
type CircleciClientListContextsResponse struct {
	PathsXxgky4ContextGetResponses200ContentApplicationJSONSchema
}

// CircleciClientListEnvVarsResponse contains the response from method CircleciClient.ListEnvVars.
type CircleciClientListEnvVarsResponse struct {
	EnvironmentVariableListResponse
}

// CircleciClientListEnvironmentVariablesFromContextResponse contains the response from method CircleciClient.ListEnvironmentVariablesFromContext.
type CircleciClientListEnvironmentVariablesFromContextResponse struct {
	Paths1S7LurdContextIDEnvironmentVariableGetResponses200ContentApplicationJSONSchema
}

// CircleciClientListMyPipelinesResponse contains the response from method CircleciClient.ListMyPipelines.
type CircleciClientListMyPipelinesResponse struct {
	PipelineListResponse1
}

// CircleciClientListPipelinesForProjectResponse contains the response from method CircleciClient.ListPipelinesForProject.
type CircleciClientListPipelinesForProjectResponse struct {
	PipelineListResponse0
}

// CircleciClientListPipelinesResponse contains the response from method CircleciClient.ListPipelines.
type CircleciClientListPipelinesResponse struct {
	PipelineListResponse
}

// CircleciClientListSchedulesForProjectResponse contains the response from method CircleciClient.ListSchedulesForProject.
type CircleciClientListSchedulesForProjectResponse struct {
	PathsOvr64LProjectSlugScheduleGetResponses200ContentApplicationJSONSchema
}

// CircleciClientListWorkflowJobsResponse contains the response from method CircleciClient.ListWorkflowJobs.
type CircleciClientListWorkflowJobsResponse struct {
	WorkflowJobListResponse
}

// CircleciClientListWorkflowsByPipelineIDResponse contains the response from method CircleciClient.ListWorkflowsByPipelineID.
type CircleciClientListWorkflowsByPipelineIDResponse struct {
	WorkflowListResponse
}

// CircleciClientRerunWorkflowResponse contains the response from method CircleciClient.RerunWorkflow.
type CircleciClientRerunWorkflowResponse struct {
	PathsOtgng0WorkflowIDRerunPostResponses202ContentApplicationJSONSchema
}

// CircleciClientTriggerPipelineResponse contains the response from method CircleciClient.TriggerPipeline.
type CircleciClientTriggerPipelineResponse struct {
	PipelineCreation
}

// CircleciClientUpdateScheduleResponse contains the response from method CircleciClient.UpdateSchedule.
type CircleciClientUpdateScheduleResponse struct {
	Schedule1
}
